//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFR_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garment()
        {
            this.VirtualFittings = new HashSet<VirtualFitting>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }
        public string Category { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VirtualFitting> VirtualFittings { get; set; }
    }
}
