//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VFR_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VirtualFitting
    {
        public int Id { get; set; }
        public int UserPhotoId { get; set; }
        public int GarmentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UserId { get; set; }
    
        public virtual Garment Garment { get; set; }
        public virtual UserPhoto UserPhoto { get; set; }
    }
}
